# Generated by Django 4.0.1 on 2022-01-10 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sobrevivente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], max_length=1)),
                ('ultima_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ultima_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
