# Generated by Django 4.0.1 on 2022-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15)),
                ('quantidade_item', models.PositiveIntegerField()),
                ('id_sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobreviventes.sobrevivente')),
            ],
        ),
    ]
